[phases.setup]
nixPkgs = ["node", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = [
  "rm -rf packages/web/dist",
  "pnpm --filter @trip avail/web build"
]

[start]
cmd = "pnpm start"
